name: Daily Newsletter Generation

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 8:00 AM UTC every day
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  generate-newsletter:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      run: python script.py  # Replace with your actual script name